### ISSUE TITLE
Tweak.xm:1:9: fatal error: '../CC.h' file not found

### ISSUE THREAD

**Issue by lbohan** [ca13ra1/CCRecord#1]
Tweak.xm:1:9: fatal error: '../CC.h' file not found

what's the problem.  can you help me 😂

**Comment by ca13ra1** [comment]
You need that header file which I don't provide. This is no error, just remove that line.

**Comment by kurt1277** [comment]
Whats the point of it being open source if you dont provide your headers?

**Comment by ca13ra1** [comment]
@kurt1277 You can easily fix this by removing the line but people clearly don't listen. Also the header has been on my GitHub for 3 days now...
